In [4]:
import numpy as np

In [5]:
ar3=np.arange(50).reshape(5,10)

In [6]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [7]:
np.sum(ar3,axis=0)#to add based on column wise axis=0

array([100, 105, 110, 115, 120, 125, 130, 135, 140, 145])

In [8]:
np.sum(ar3,axis=1) #to add based on row wise axis=1 

array([ 45, 145, 245, 345, 445])

In [9]:
np.sum(ar3)

1225

In [ ]:
#mean-->average
#median-->center value
#mode-->max num of repeated element
#variance-->median/total num of elemnts
#std-->square root of variance


In [10]:
#linspace()-->to print the evenly seperated pointed
#btw 2 range of values 
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [11]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [14]:
np.linspace(1,10,4,dtype=int)#--linspace9start,end,num of values)

array([ 1,  4,  7, 10])

In [18]:
np.linspace(12,30,13,retstep=True)

(array([12. , 13.5, 15. , 16.5, 18. , 19.5, 21. , 22.5, 24. , 25.5, 27. ,
        28.5, 30. ]),
 1.5)

In [30]:
#random module
#To generate random number between the range
#np.random.randint(start,end,num of values)
#np.random.randint(40)
#or
np.random.randint(20,30, 3)

array([21, 22, 23])

In [31]:
#rand() -->
#To get the randomly generated values from 0 to 1,based on uniform distribution

np.random.rand(4)

array([0.34940694, 0.00409392, 0.40373448, 0.86745024])

In [33]:
#randn()-->
#To get the randomly generated values from 0 to 1,based on normalised distribution

np.random.randn(5,4)


array([[ 0.08731491,  0.97820762, -0.02782991, -0.85087551],
       [-1.0406614 ,  1.08075763, -0.05789148,  0.38464747],
       [-0.73396706, -1.30069621,  1.025213  , -0.10404806],
       [-1.46964046,  1.36730417,  0.9336541 ,  0.65479886],
       [ 1.13930318,  0.16424539, -2.22905485,  0.14844804]])

In [34]:
ar3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [35]:
ar3.min()

0

In [36]:
ar3.max()

49

In [40]:
#To find the index of min and max values in an array we use argmin ,argmax
l1=[56,89,90,67,45]
np1=np.array(l1)
print(np1.argmin())
print(np1.argmax())


4
2


In [41]:
np1

array([56, 89, 90, 67, 45])

In [42]:
np.sin(np1)
np.cos(np1)
np.tan(np1)

array([-0.61127369,  1.68582537, -1.99520041,  1.65231726,  1.61977519])

In [43]:
np.sin(np1)

array([-0.521551  ,  0.86006941,  0.89399666, -0.85551998,  0.85090352])

In [44]:
1/np.tan(np1)--cot(np1)

array([-1.63592842,  0.59318125, -0.50120278,  0.60521065,  0.61736962])

In [55]:
#task:1->write python code for the below logic
np2=np.array([1,2,3])
np3=np.array([4,5,6])


len1=len(np2)
len2=len(np3)


diff=abs(len1-len2)
for val in range(diff):
    np3=np.append(np3, 1)
np.sum((np2*np3))
#(1x4)+(2x5)+(3x6)=4+10+18=>32
#ar4=(np2[0]*np3[0])+(np2[1]*np3[1])+(np2[2]*np3[2])
#ar4

32

In [52]:
##fname=np.array(["sid","fn1","fn2"],dtype=str)
#name=np.array(['T',"ln1","ln2"],dtype=str)



In [ ]:
np1=np.array([1,34,56,78,np.nan,np.nan])

In [58]:
#To eliminate nan values
np1[~np.isnan(np1)]

array([56, 89, 90, 67, 45])

In [59]:
np1[np.isnan(np1)]

array([], dtype=int32)