In [7]:
import numpy as np
L=r=[[1,2,3],[45,4,7],[9,6,10]]
arr=np.array(L)
arr

array([[ 1,  2,  3],
       [45,  4,  7],
       [ 9,  6, 10]])

In [9]:
import numpy as np
ar1=np.append(arr,[12,23,45],axis=None)
ar1

array([ 1,  2,  3, 45,  4,  7,  9,  6, 10, 12, 23, 45])

In [10]:
#2.)Find the frequency of all element in the series
#se = pd.Series([1,1,1,2,2,2,2,3,3,3,4,4,5])
import pandas as pd
se=pd.Series([1,1,1,2,2,2,2,3,3,3,4,4,5])
result=se.mode()
print(result)

0    2
dtype: int64


In [11]:
#3.)Reshape the series ser into a dataframe
import pandas as pd
ser = pd.Series(np.random.randint(1, 10, 35))
ser.to_frame()

0
0   4
1   6
2   9
3   2
4   6
5   5
6   7
7   3
8   1
9   6
10  9
11  3
12  4
13  8
14  2
15  2
16  7
17  1
18  9
19  6
20  4
21  2
22  6
23  2
24  1
25  1
26  9
27  2
28  1
29  4
30  9
31  2
32  4
33  1
34  4

In [12]:
#4.)Find the positions of numbers that are multiples of 3 from ser
import pandas as pfd
ser = pd.Series(np.random.randint(1, 10, 10))
ser

0    5
1    9
2    9
3    5
4    8
5    1
6    2
7    4
8    8
9    1
dtype: int32

In [13]:
result = np.where(ser % 3==0)
print("Positions of numbers that are multiples of 3:")
print(result)

Positions of numbers that are multiples of 3:
(array([1, 2], dtype=int64),)


In [14]:
#5.) Join the two series
import pandas as pd
ser1 = pd.Series(range(5))
ser1=ser1.astype(str)
ser1

0    0
1    1
2    2
3    3
4    4
dtype: object

In [15]:
import pandas as pd 
ser2 = pd.Series(list('abcde'))
ser2

0    a
1    b
2    c
3    d
4    e
dtype: object

In [16]:
ser1+ser2

0    0a
1    1b
2    2c
3    3d
4    4e
dtype: object

In [18]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}

In [23]:
import pandas as pd
df=pd.DataFrame(data=exam_data)
df

name  score  attempts qualify
0  Anastasia   12.5         1     yes
1       Dima    9.0         3      no
2  Katherine   16.5         2     yes
3      James    NaN         3      no
4      Emily    9.0         2      no
5    Michael   20.0         3     yes
6    Matthew   14.5         1     yes
7      Laura    NaN         1      no
8      Kevin    8.0         2      no
9      Jonas   19.0         1     yes

In [24]:
df['name']

0    Anastasia
1         Dima
2    Katherine
3        James
4        Emily
5      Michael
6      Matthew
7        Laura
8        Kevin
9        Jonas
Name: name, dtype: object

In [25]:
df['score']

0    12.5
1     9.0
2    16.5
3     NaN
4     9.0
5    20.0
6    14.5
7     NaN
8     8.0
9    19.0
Name: score, dtype: float64

In [26]:
df[['name','score']]

name  score
0  Anastasia   12.5
1       Dima    9.0
2  Katherine   16.5
3      James    NaN
4      Emily    9.0
5    Michael   20.0
6    Matthew   14.5
7      Laura    NaN
8      Kevin    8.0
9      Jonas   19.0