In [4]:
import numpy as np
ar1=np.arange(13)


In [5]:
ar1
len (ar1)

13

In [7]:
#identity can be  created using two functions
#eye()--> used to define both user defined rows and columns
#identity()--> used to define same number of rows and columns
#syntax-->np.identity(5)-->5 is 5 rows nad columns
#syntax->>np.eye(3,4)-->3 rows and 4 columns
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [9]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
reshaped_array=ar1.reshape (13,1)


In [13]:
reshaped_array

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [14]:
#slicing
np.identity(5,dtype=complex)

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])

In [18]:
#To perform multidimensional slicing
ar2=np.arange(25).reshape(5,5)

In [19]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ar2.shape

(5, 5)

In [22]:
#ar2[rows,columns,step]
#ar2[row_start:row_end,col_start,col_end,step]
ar2[0:3, 1:4]


array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [24]:
ar2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
ar2[1:3,1:3]

array([[ 6,  7],
       [11, 12]])

In [30]:
ar2[-4:-2]

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
ar2[-4:-2,-4:-2]

array([[ 6,  7],
       [11, 12]])